repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: []
      python_version: python3.6
-   repo: git://github.com/luismayta/pre-commit-mypy
    sha: '76dec333d8aaee9fc5c92707fdd12efcd0df9a5c'
    hooks:
    -   id: mypy
        exclude: "docs"
        args:
        - --ignore-missing-imports
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    -   id: isort
