site_name: "DESDEO documentation"
repo_url: "https://github.com/industrial-optimization-group/DESDEO"
repo_name: "GitHub"
docs_dir: "docs"
site_dir: "site"

nav:
  - Home: "index.md"
  - "User Guide":
      - "Defining a multiobjective optimization problem": "howtoguides/problem.md"
  - "Explanation":
      - "The problem format": "explanation/problem_format.md"
      - "Scalarization-based methods": "explanation/scalarization_methods.md"
      - "Solving problems": "explanation/solving_problems.md"

theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - python
  locale: en

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search

markdown_extensions:
  - admonition
  - mdx_math
