site_name: "DESDEO documentation"
repo_url: "https://github.com/industrial-optimization-group/DESDEO"
repo_name: "GitHub"
docs_dir: "docs"
site_dir: "site"

nav:
  - "DESDEO":
      - "About": "home/about.md"
      - "The structure": "home/structure.md"
      - "Citing DESDEO": "home/citing.md"
  - "Tutorials":
      - "A primer on multiobjective optimization": "tutorials/moo_primer.md"
      - "Installing DESDEO": "tutorials/installing.md"
      - "Contributing to DESDEO": "tutorials/contributing.md"
  - "Explanation":
      - "The problem format": "explanation/problem_format.md"
      - "Parsing and evaluating": "explanation/parsing_and_evaluating.md"
      - "Scalarization": "explanation/scalarization.md"
      - "Solvers": "explanation/solvers.md"
  - "User Guide":
      - "How to define multiobjective optimization problems": "howtoguides/problem.md"
      - "How to run DESDEO's web API": "howtoguides/api.md"
      - "How to use the NAUTILUS Navigator method": "howtoguides/NAUTILUS Navigator.md"
  - "API Reference":
      - "desdeo-problem": "api/desdeo_problem.md"
      - "desdeo-tools": "api/desdeo_tools.md"
      - "desdeo-mcdm": "api/desdeo_mcdm.md"
      - "desdeo-emo": "api/desdeo_emo.md"
      - "desdeo-api": "api/desdeo_api.md"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - palette.switch
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - python
  locale: en
  palette:
    scheme: slate
    primary: black
  logo: assets/desdeo_logo.png
  favicon: assets/desdeo_logo.png

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - extrajs/extra.js

plugins:
  - search
  - autorefs
  - macros:
      module_name: docs/macros
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_bases: true
            show_signature_annotations: true
            show_type_annotations: true
            show_root_heading: true
            separate_signature: true
            heading_level: 2
            merge_init_into_class: true
            show_root_toc_entry: false
            group_by_category: true
            show_category_heading: false
            show_symbol_type_heading: true
            show_symbol_type_doc: true
            filters: none
          docstring_options:
           ignore_init_summary: true

markdown_extensions:
  - admonition
  - mdx_math
  - pymdownx.arithmatex:
      generic: true 

extra_css:
  - stylesheets/extra.css 
