site_name: "DESDEO documentation"
repo_url: "https://github.com/industrial-optimization-group/DESDEO"
repo_name: "GitHub"
docs_dir: "docs"
site_dir: "site"

nav:
  - Home: "index.md"
  - "User Guide":
      - "Defining multiobjective optimization problems": "howtoguides/problem.md"
      - "Running the API": "howtoguides/api.md"
      - "How to use the NAUTILUS Navigator method": "howtoguides/NAUTILUS Navigator.md"
  - "Explanation":
      - "The problem format": "explanation/problem_format.md"
      - "Parsing and evaluating": "explanation/parsing_and_evaluating.md"
      - "Scalarization": "explanation/scalarization.md"
      - "Solvers": "explanation/solvers.md"
  - "API Documentation":
      - "desdeo-problem": "api/desdeo_problem.md"

theme:
  name: material
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - python
  locale: en

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - macros:
      module_name: docs/macros
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_signature_annotations: true
            show_type_annotations: true
            show_root_heading: false
            separate_signature: true
            heading_level: 2
            merge_init_into_class: true
            show_root_toc_entry: false
            group_by_category: true
            show_category_heading: false
            filters: none
          docstring_options:
           ignore_init_summary: true

markdown_extensions:
  - admonition
  - mdx_math
