site_name: "DESDEO documentation"
repo_url: "https://github.com/industrial-optimization-group/DESDEO"
repo_name: "GitHub"
docs_dir: "docs"
site_dir: "site"

nav:
  - Home: "index.md"
  - "User Guide":
      - "Defining multiobjective optimization problems": "howtoguides/problem.md"
      - "Running the API": "howtoguides/api.md"
      - "How to use the NAUTILUS Navigator method": "howtoguides/NAUTILUS Navigator.md"
  - "Explanation":
      - "The problem format": "explanation/problem_format.md"
      - "Parsing and evaluating": "explanation/parsing_and_evaluating.md"
      - "Scalarization": "explanation/scalarization.md"
      - "Solvers": "explanation/solvers.md"

theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - python
  locale: en

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - search
  - macros:
      module_name: docs/macros

markdown_extensions:
  - admonition
  - mdx_math
